# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(571, 400)
        Dialog.setSizeGripEnabled(False)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout_10.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.settingsTab = QtWidgets.QWidget()
        self.settingsTab.setObjectName("settingsTab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.settingsTab)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.settingsLayout = QtWidgets.QGridLayout()
        self.settingsLayout.setContentsMargins(11, 11, 11, 11)
        self.settingsLayout.setSpacing(6)
        self.settingsLayout.setObjectName("settingsLayout")
        self.publicNameLbl = QtWidgets.QLabel(self.settingsTab)
        self.publicNameLbl.setObjectName("publicNameLbl")
        self.settingsLayout.addWidget(self.publicNameLbl, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.publicNameInput = QtWidgets.QLineEdit(self.settingsTab)
        self.publicNameInput.setObjectName("publicNameInput")
        self.settingsLayout.addWidget(self.publicNameInput, 0, 1, 1, 1)
        self.portLbl = QtWidgets.QLabel(self.settingsTab)
        self.portLbl.setObjectName("portLbl")
        self.settingsLayout.addWidget(self.portLbl, 0, 2, 1, 1)
        self.port = QtWidgets.QSpinBox(self.settingsTab)
        self.port.setMinimum(1025)
        self.port.setMaximum(65535)
        self.port.setProperty("value", 2121)
        self.port.setObjectName("port")
        self.settingsLayout.addWidget(self.port, 0, 3, 1, 1)
        self.sharedLocationBtn = QtWidgets.QPushButton(self.settingsTab)
        self.sharedLocationBtn.setObjectName("sharedLocationBtn")
        self.settingsLayout.addWidget(self.sharedLocationBtn, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.speedLimitLbl = QtWidgets.QLabel(self.settingsTab)
        self.speedLimitLbl.setObjectName("speedLimitLbl")
        self.settingsLayout.addWidget(self.speedLimitLbl, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.speedLimitSpin = QtWidgets.QSpinBox(self.settingsTab)
        self.speedLimitSpin.setMinimum(2)
        self.speedLimitSpin.setMaximum(100)
        self.speedLimitSpin.setObjectName("speedLimitSpin")
        self.settingsLayout.addWidget(self.speedLimitSpin, 2, 3, 1, 1)
        self.downloadLocationBtn = QtWidgets.QPushButton(self.settingsTab)
        self.downloadLocationBtn.setObjectName("downloadLocationBtn")
        self.settingsLayout.addWidget(self.downloadLocationBtn, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.exchangeURLLbl = QtWidgets.QLabel(self.settingsTab)
        self.exchangeURLLbl.setObjectName("exchangeURLLbl")
        self.settingsLayout.addWidget(self.exchangeURLLbl, 4, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.sharedLocationInput = QtWidgets.QLineEdit(self.settingsTab)
        self.sharedLocationInput.setObjectName("sharedLocationInput")
        self.settingsLayout.addWidget(self.sharedLocationInput, 1, 1, 1, 3)
        self.speedLimitSlider = QtWidgets.QSlider(self.settingsTab)
        self.speedLimitSlider.setMinimum(2)
        self.speedLimitSlider.setMaximum(10)
        self.speedLimitSlider.setOrientation(QtCore.Qt.Horizontal)
        self.speedLimitSlider.setObjectName("speedLimitSlider")
        self.settingsLayout.addWidget(self.speedLimitSlider, 2, 1, 1, 2)
        self.downloadLocationInput = QtWidgets.QLineEdit(self.settingsTab)
        self.downloadLocationInput.setObjectName("downloadLocationInput")
        self.settingsLayout.addWidget(self.downloadLocationInput, 3, 1, 1, 3)
        self.exchangeURLInput = QtWidgets.QLineEdit(self.settingsTab)
        self.exchangeURLInput.setObjectName("exchangeURLInput")
        self.settingsLayout.addWidget(self.exchangeURLInput, 4, 1, 1, 3)
        self.verticalLayout.addLayout(self.settingsLayout)
        self.mouseMessageLayout = QtWidgets.QHBoxLayout()
        self.mouseMessageLayout.setContentsMargins(11, 11, 11, 11)
        self.mouseMessageLayout.setSpacing(6)
        self.mouseMessageLayout.setObjectName("mouseMessageLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.mouseMessageLayout.addItem(spacerItem)
        self.label_5 = QtWidgets.QLabel(self.settingsTab)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.mouseMessageLayout.addWidget(self.label_5)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.mouseMessageLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.mouseMessageLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.toggleShareBtn = QtWidgets.QPushButton(self.settingsTab)
        self.toggleShareBtn.setDefault(True)
        self.toggleShareBtn.setObjectName("toggleShareBtn")
        self.horizontalLayout_3.addWidget(self.toggleShareBtn)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.groupBox = QtWidgets.QGroupBox(self.settingsTab)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.connectedStatsLbl = QtWidgets.QLabel(self.groupBox)
        self.connectedStatsLbl.setObjectName("connectedStatsLbl")
        self.horizontalLayout_8.addWidget(self.connectedStatsLbl)
        self.line_3 = QtWidgets.QFrame(self.groupBox)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_8.addWidget(self.line_3)
        self.stats_connected = QtWidgets.QLabel(self.groupBox)
        self.stats_connected.setObjectName("stats_connected")
        self.horizontalLayout_8.addWidget(self.stats_connected)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(5)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.horizontalLayout_8.addWidget(self.line)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.line_5 = QtWidgets.QFrame(self.groupBox)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_8.addWidget(self.line_5)
        self.stats_files = QtWidgets.QLabel(self.groupBox)
        self.stats_files.setObjectName("stats_files")
        self.horizontalLayout_8.addWidget(self.stats_files)
        self.line_4 = QtWidgets.QFrame(self.groupBox)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_8.addWidget(self.line_4)
        self.stats_bytes = QtWidgets.QLabel(self.groupBox)
        self.stats_bytes.setObjectName("stats_bytes")
        self.horizontalLayout_8.addWidget(self.stats_bytes)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.verticalLayout.addWidget(self.groupBox)
        self.tabWidget.addTab(self.settingsTab, "")
        self.usersListTab = QtWidgets.QWidget()
        self.usersListTab.setObjectName("usersListTab")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.usersListTab)
        self.horizontalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.userListScrollArea = QtWidgets.QScrollArea(self.usersListTab)
        self.userListScrollArea.setWidgetResizable(True)
        self.userListScrollArea.setObjectName("userListScrollArea")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 529, 333))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_4)
        self.gridLayout_7.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.currentUsersGrid = QtWidgets.QGridLayout()
        self.currentUsersGrid.setContentsMargins(11, 11, 11, 11)
        self.currentUsersGrid.setSpacing(6)
        self.currentUsersGrid.setObjectName("currentUsersGrid")
        self.gridLayout_7.addLayout(self.currentUsersGrid, 0, 0, 1, 1)
        self.userListScrollArea.setWidget(self.scrollAreaWidgetContents_4)
        self.horizontalLayout_5.addWidget(self.userListScrollArea)
        self.tabWidget.addTab(self.usersListTab, "")
        self.browserTab = QtWidgets.QWidget()
        self.browserTab.setObjectName("browserTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.browserTab)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.browserControlsLayout = QtWidgets.QHBoxLayout()
        self.browserControlsLayout.setContentsMargins(11, 11, 11, 11)
        self.browserControlsLayout.setSpacing(6)
        self.browserControlsLayout.setObjectName("browserControlsLayout")
        self.browserPrevBtn = QtWidgets.QPushButton(self.browserTab)
        self.browserPrevBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.browserPrevBtn.setIcon(icon)
        self.browserPrevBtn.setObjectName("browserPrevBtn")
        self.browserControlsLayout.addWidget(self.browserPrevBtn)
        self.browserHomeBtn = QtWidgets.QPushButton(self.browserTab)
        self.browserHomeBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.browserHomeBtn.setIcon(icon1)
        self.browserHomeBtn.setObjectName("browserHomeBtn")
        self.browserControlsLayout.addWidget(self.browserHomeBtn)
        self.browserInput = QtWidgets.QLineEdit(self.browserTab)
        self.browserInput.setObjectName("browserInput")
        self.browserControlsLayout.addWidget(self.browserInput)
        self.browserGoBtn = QtWidgets.QPushButton(self.browserTab)
        self.browserGoBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/go.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.browserGoBtn.setIcon(icon2)
        self.browserGoBtn.setObjectName("browserGoBtn")
        self.browserControlsLayout.addWidget(self.browserGoBtn)
        self.verticalLayout_2.addLayout(self.browserControlsLayout)
        self.browserScrollArea = QtWidgets.QScrollArea(self.browserTab)
        self.browserScrollArea.setWidgetResizable(True)
        self.browserScrollArea.setObjectName("browserScrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 529, 298))
        self.scrollAreaWidgetContents_2.setStyleSheet("")
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.browserGrid = QtWidgets.QGridLayout()
        self.browserGrid.setContentsMargins(11, 11, 11, 11)
        self.browserGrid.setSpacing(6)
        self.browserGrid.setObjectName("browserGrid")
        self.gridLayout_3.addLayout(self.browserGrid, 0, 0, 1, 1)
        self.browserScrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.addWidget(self.browserScrollArea)
        self.tabWidget.addTab(self.browserTab, "")
        self.downloadsTab = QtWidgets.QWidget()
        self.downloadsTab.setObjectName("downloadsTab")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.downloadsTab)
        self.horizontalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.downloadsScrollArea = QtWidgets.QScrollArea(self.downloadsTab)
        self.downloadsScrollArea.setWidgetResizable(True)
        self.downloadsScrollArea.setObjectName("downloadsScrollArea")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 529, 333))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_5.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.downloadsLayout = QtWidgets.QVBoxLayout()
        self.downloadsLayout.setContentsMargins(11, 11, 11, 11)
        self.downloadsLayout.setSpacing(6)
        self.downloadsLayout.setObjectName("downloadsLayout")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.downloadsLayout.addItem(spacerItem4)
        self.gridLayout_5.addLayout(self.downloadsLayout, 0, 0, 1, 1)
        self.downloadsScrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_7.addWidget(self.downloadsScrollArea)
        self.tabWidget.addTab(self.downloadsTab, "")
        self.horizontalLayout_10.addWidget(self.tabWidget)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.publicNameInput, self.port)
        Dialog.setTabOrder(self.port, self.sharedLocationBtn)
        Dialog.setTabOrder(self.sharedLocationBtn, self.sharedLocationInput)
        Dialog.setTabOrder(self.sharedLocationInput, self.speedLimitSlider)
        Dialog.setTabOrder(self.speedLimitSlider, self.speedLimitSpin)
        Dialog.setTabOrder(self.speedLimitSpin, self.downloadLocationBtn)
        Dialog.setTabOrder(self.downloadLocationBtn, self.downloadLocationInput)
        Dialog.setTabOrder(self.downloadLocationInput, self.exchangeURLInput)
        Dialog.setTabOrder(self.exchangeURLInput, self.toggleShareBtn)
        Dialog.setTabOrder(self.toggleShareBtn, self.browserInput)
        Dialog.setTabOrder(self.browserInput, self.browserGoBtn)
        Dialog.setTabOrder(self.browserGoBtn, self.browserScrollArea)
        Dialog.setTabOrder(self.browserScrollArea, self.downloadsScrollArea)
        Dialog.setTabOrder(self.downloadsScrollArea, self.userListScrollArea)
        Dialog.setTabOrder(self.userListScrollArea, self.browserPrevBtn)
        Dialog.setTabOrder(self.browserPrevBtn, self.browserHomeBtn)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.publicNameLbl.setText(_translate("Dialog", "Public Name"))
        self.publicNameInput.setPlaceholderText(_translate("Dialog", "How do people know you?"))
        self.portLbl.setText(_translate("Dialog", "Port"))
        self.sharedLocationBtn.setText(_translate("Dialog", "Select Shared Location"))
        self.speedLimitLbl.setText(_translate("Dialog", "Speed Limit"))
        self.speedLimitSpin.setSuffix(_translate("Dialog", " Mbps"))
        self.downloadLocationBtn.setText(_translate("Dialog", "Select Download Location"))
        self.exchangeURLLbl.setText(_translate("Dialog", "Exchange URL"))
        self.sharedLocationInput.setPlaceholderText(_translate("Dialog", "This is the folder you are sharing"))
        self.downloadLocationInput.setPlaceholderText(_translate("Dialog", "Leave it blank to set everytime you download"))
        self.exchangeURLInput.setPlaceholderText(_translate("Dialog", "You can get it from your exchange website"))
        self.label_5.setText(_translate("Dialog", "Don\'t randomly hit your mouse. It hurts!"))
        self.toggleShareBtn.setText(_translate("Dialog", "Toggle Share"))
        self.groupBox.setTitle(_translate("Dialog", "     Stats:"))
        self.connectedStatsLbl.setText(_translate("Dialog", "Connected"))
        self.stats_connected.setText(_translate("Dialog", "TextLabel"))
        self.label_8.setText(_translate("Dialog", "Transferred"))
        self.stats_files.setText(_translate("Dialog", "TextLabel"))
        self.stats_bytes.setText(_translate("Dialog", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settingsTab), _translate("Dialog", "Settings"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.usersListTab), _translate("Dialog", "Current Users"))
        self.browserInput.setPlaceholderText(_translate("Dialog", "Search / Enter path"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.browserTab), _translate("Dialog", "Browser"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.downloadsTab), _translate("Dialog", "Downloads"))

import resources_rc
