# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(595, 457)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(mainWindow)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tabWidget = QtWidgets.QTabWidget(mainWindow)
        self.tabWidget.setObjectName("tabWidget")
        self.settingsTab = QtWidgets.QWidget()
        self.settingsTab.setObjectName("settingsTab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.settingsTab)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.settingsLayout = QtWidgets.QGridLayout()
        self.settingsLayout.setContentsMargins(5, 5, 5, 5)
        self.settingsLayout.setObjectName("settingsLayout")
        self.publicNameLbl = QtWidgets.QLabel(self.settingsTab)
        self.publicNameLbl.setObjectName("publicNameLbl")
        self.settingsLayout.addWidget(self.publicNameLbl, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.publicNameInput = QtWidgets.QLineEdit(self.settingsTab)
        self.publicNameInput.setObjectName("publicNameInput")
        self.settingsLayout.addWidget(self.publicNameInput, 0, 1, 1, 1)
        self.portLbl = QtWidgets.QLabel(self.settingsTab)
        self.portLbl.setObjectName("portLbl")
        self.settingsLayout.addWidget(self.portLbl, 0, 2, 1, 1)
        self.port = QtWidgets.QSpinBox(self.settingsTab)
        self.port.setMinimum(1025)
        self.port.setMaximum(65535)
        self.port.setProperty("value", 2121)
        self.port.setObjectName("port")
        self.settingsLayout.addWidget(self.port, 0, 3, 1, 1)
        self.sharedLocationBtn = QtWidgets.QPushButton(self.settingsTab)
        self.sharedLocationBtn.setAutoDefault(False)
        self.sharedLocationBtn.setObjectName("sharedLocationBtn")
        self.settingsLayout.addWidget(self.sharedLocationBtn, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.speedLimitLbl = QtWidgets.QLabel(self.settingsTab)
        self.speedLimitLbl.setObjectName("speedLimitLbl")
        self.settingsLayout.addWidget(self.speedLimitLbl, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.speedLimitSpin = QtWidgets.QSpinBox(self.settingsTab)
        self.speedLimitSpin.setMinimum(2)
        self.speedLimitSpin.setMaximum(10)
        self.speedLimitSpin.setSingleStep(1)
        self.speedLimitSpin.setObjectName("speedLimitSpin")
        self.settingsLayout.addWidget(self.speedLimitSpin, 2, 3, 1, 1)
        self.downloadLocationBtn = QtWidgets.QPushButton(self.settingsTab)
        self.downloadLocationBtn.setAutoDefault(False)
        self.downloadLocationBtn.setObjectName("downloadLocationBtn")
        self.settingsLayout.addWidget(self.downloadLocationBtn, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.exchangeURLLbl = QtWidgets.QLabel(self.settingsTab)
        self.exchangeURLLbl.setObjectName("exchangeURLLbl")
        self.settingsLayout.addWidget(self.exchangeURLLbl, 4, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.sharedLocationInput = QtWidgets.QLineEdit(self.settingsTab)
        self.sharedLocationInput.setObjectName("sharedLocationInput")
        self.settingsLayout.addWidget(self.sharedLocationInput, 1, 1, 1, 3)
        self.speedLimitSlider = QtWidgets.QSlider(self.settingsTab)
        self.speedLimitSlider.setMinimum(2)
        self.speedLimitSlider.setMaximum(10)
        self.speedLimitSlider.setSingleStep(2)
        self.speedLimitSlider.setOrientation(QtCore.Qt.Horizontal)
        self.speedLimitSlider.setInvertedAppearance(False)
        self.speedLimitSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.speedLimitSlider.setTickInterval(1)
        self.speedLimitSlider.setObjectName("speedLimitSlider")
        self.settingsLayout.addWidget(self.speedLimitSlider, 2, 1, 1, 2)
        self.downloadLocationInput = QtWidgets.QLineEdit(self.settingsTab)
        self.downloadLocationInput.setObjectName("downloadLocationInput")
        self.settingsLayout.addWidget(self.downloadLocationInput, 3, 1, 1, 3)
        self.exchangeURLInput = QtWidgets.QLineEdit(self.settingsTab)
        self.exchangeURLInput.setToolTip("")
        self.exchangeURLInput.setObjectName("exchangeURLInput")
        self.settingsLayout.addWidget(self.exchangeURLInput, 4, 1, 1, 3)
        self.verticalLayout.addLayout(self.settingsLayout)
        self.mouseMessageLayout = QtWidgets.QHBoxLayout()
        self.mouseMessageLayout.setObjectName("mouseMessageLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.mouseMessageLayout.addItem(spacerItem)
        self.label_5 = QtWidgets.QLabel(self.settingsTab)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.mouseMessageLayout.addWidget(self.label_5)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.mouseMessageLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.mouseMessageLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.toggleShareBtn = QtWidgets.QPushButton(self.settingsTab)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/failed.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toggleShareBtn.setIcon(icon1)
        self.toggleShareBtn.setDefault(True)
        self.toggleShareBtn.setObjectName("toggleShareBtn")
        self.horizontalLayout_3.addWidget(self.toggleShareBtn)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.urlFrame = QtWidgets.QFrame(self.settingsTab)
        self.urlFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.urlFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.urlFrame.setObjectName("urlFrame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.urlFrame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.label_2 = QtWidgets.QLabel(self.urlFrame)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.urlLabel = QtWidgets.QLabel(self.urlFrame)
        self.urlLabel.setObjectName("urlLabel")
        self.horizontalLayout_5.addWidget(self.urlLabel)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.verticalLayout.addWidget(self.urlFrame)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.line_6 = QtWidgets.QFrame(self.settingsTab)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setObjectName("line_6")
        self.verticalLayout.addWidget(self.line_6)
        self.groupBox = QtWidgets.QGroupBox(self.settingsTab)
        self.groupBox.setStyleSheet("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.connectedStatsLbl = QtWidgets.QLabel(self.groupBox)
        self.connectedStatsLbl.setObjectName("connectedStatsLbl")
        self.horizontalLayout_8.addWidget(self.connectedStatsLbl)
        self.line_3 = QtWidgets.QFrame(self.groupBox)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_8.addWidget(self.line_3)
        self.stats_connected = QtWidgets.QLabel(self.groupBox)
        self.stats_connected.setObjectName("stats_connected")
        self.horizontalLayout_8.addWidget(self.stats_connected)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(5)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.horizontalLayout_8.addWidget(self.line)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.line_5 = QtWidgets.QFrame(self.groupBox)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_8.addWidget(self.line_5)
        self.stats_files = QtWidgets.QLabel(self.groupBox)
        self.stats_files.setObjectName("stats_files")
        self.horizontalLayout_8.addWidget(self.stats_files)
        self.line_4 = QtWidgets.QFrame(self.groupBox)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_8.addWidget(self.line_4)
        self.stats_bytes = QtWidgets.QLabel(self.groupBox)
        self.stats_bytes.setObjectName("stats_bytes")
        self.horizontalLayout_8.addWidget(self.stats_bytes)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.verticalLayout.addWidget(self.groupBox)
        self.trayCB = QtWidgets.QCheckBox(self.settingsTab)
        self.trayCB.setChecked(True)
        self.trayCB.setObjectName("trayCB")
        self.verticalLayout.addWidget(self.trayCB)
        self.line_2 = QtWidgets.QFrame(self.settingsTab)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.externalLinksLayout = QtWidgets.QHBoxLayout()
        self.externalLinksLayout.setContentsMargins(-1, 0, -1, 0)
        self.externalLinksLayout.setObjectName("externalLinksLayout")
        self.projectLink = QtWidgets.QLabel(self.settingsTab)
        self.projectLink.setObjectName("projectLink")
        self.externalLinksLayout.addWidget(self.projectLink)
        self.developerLink = QtWidgets.QLabel(self.settingsTab)
        self.developerLink.setTextFormat(QtCore.Qt.RichText)
        self.developerLink.setOpenExternalLinks(False)
        self.developerLink.setObjectName("developerLink")
        self.externalLinksLayout.addWidget(self.developerLink)
        self.verticalLayout.addLayout(self.externalLinksLayout)
        self.tabWidget.addTab(self.settingsTab, "")
        self.usersListTab = QtWidgets.QWidget()
        self.usersListTab.setObjectName("usersListTab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.usersListTab)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 5, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.usersListTab)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem7 = QtWidgets.QSpacerItem(148, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.reloadUsersBtn = QtWidgets.QPushButton(self.usersListTab)
        self.reloadUsersBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/reload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reloadUsersBtn.setIcon(icon2)
        self.reloadUsersBtn.setObjectName("reloadUsersBtn")
        self.horizontalLayout_2.addWidget(self.reloadUsersBtn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.userListTable = QtWidgets.QTableWidget(self.usersListTab)
        self.userListTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.userListTable.setGridStyle(QtCore.Qt.DashLine)
        self.userListTable.setColumnCount(3)
        self.userListTable.setObjectName("userListTable")
        self.userListTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.userListTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.userListTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.userListTable.setHorizontalHeaderItem(2, item)
        self.userListTable.horizontalHeader().setMinimumSectionSize(20)
        self.userListTable.horizontalHeader().setStretchLastSection(True)
        self.userListTable.verticalHeader().setVisible(False)
        self.userListTable.verticalHeader().setDefaultSectionSize(30)
        self.userListTable.verticalHeader().setSortIndicatorShown(False)
        self.verticalLayout_4.addWidget(self.userListTable)
        self.tabWidget.addTab(self.usersListTab, "")
        self.browserTab = QtWidgets.QWidget()
        self.browserTab.setObjectName("browserTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.browserTab)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 5, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.browserHomeBtn = QtWidgets.QPushButton(self.browserTab)
        self.browserHomeBtn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.browserHomeBtn.setIcon(icon3)
        self.browserHomeBtn.setObjectName("browserHomeBtn")
        self.horizontalLayout.addWidget(self.browserHomeBtn)
        self.browserPrevBtn = QtWidgets.QPushButton(self.browserTab)
        self.browserPrevBtn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.browserPrevBtn.setIcon(icon4)
        self.browserPrevBtn.setObjectName("browserPrevBtn")
        self.horizontalLayout.addWidget(self.browserPrevBtn)
        self.browserInput = QtWidgets.QLineEdit(self.browserTab)
        self.browserInput.setObjectName("browserInput")
        self.horizontalLayout.addWidget(self.browserInput)
        self.browserGoBtn = QtWidgets.QPushButton(self.browserTab)
        self.browserGoBtn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/go.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.browserGoBtn.setIcon(icon5)
        self.browserGoBtn.setObjectName("browserGoBtn")
        self.horizontalLayout.addWidget(self.browserGoBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.browserTable = QtWidgets.QTableWidget(self.browserTab)
        self.browserTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.browserTable.setAlternatingRowColors(True)
        self.browserTable.setGridStyle(QtCore.Qt.DashLine)
        self.browserTable.setObjectName("browserTable")
        self.browserTable.setColumnCount(5)
        self.browserTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.browserTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.browserTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.browserTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.browserTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.browserTable.setHorizontalHeaderItem(4, item)
        self.browserTable.horizontalHeader().setStretchLastSection(True)
        self.browserTable.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.browserTable)
        self.tabWidget.addTab(self.browserTab, "")
        self.downloadsTab = QtWidgets.QWidget()
        self.downloadsTab.setObjectName("downloadsTab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.downloadsTab)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.downloadsScrollArea = QtWidgets.QScrollArea(self.downloadsTab)
        self.downloadsScrollArea.setAutoFillBackground(False)
        self.downloadsScrollArea.setWidgetResizable(True)
        self.downloadsScrollArea.setObjectName("downloadsScrollArea")
        self.downloadsScrollAreaContainer = QtWidgets.QWidget()
        self.downloadsScrollAreaContainer.setGeometry(QtCore.QRect(0, 0, 553, 390))
        self.downloadsScrollAreaContainer.setObjectName("downloadsScrollAreaContainer")
        self.downloadsLayout = QtWidgets.QVBoxLayout(self.downloadsScrollAreaContainer)
        self.downloadsLayout.setContentsMargins(0, 0, 0, 0)
        self.downloadsLayout.setObjectName("downloadsLayout")
        spacerItem8 = QtWidgets.QSpacerItem(20, 331, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.downloadsLayout.addItem(spacerItem8)
        self.downloadsScrollArea.setWidget(self.downloadsScrollAreaContainer)
        self.verticalLayout_5.addWidget(self.downloadsScrollArea)
        self.tabWidget.addTab(self.downloadsTab, "")
        self.verticalLayout_6.addWidget(self.tabWidget)

        self.retranslateUi(mainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "21Lane"))
        self.publicNameLbl.setText(_translate("mainWindow", "Public Name"))
        self.publicNameInput.setPlaceholderText(_translate("mainWindow", "How do people know you?"))
        self.portLbl.setText(_translate("mainWindow", "Port"))
        self.sharedLocationBtn.setText(_translate("mainWindow", "Select Shared Location"))
        self.speedLimitLbl.setText(_translate("mainWindow", "Speed Limit"))
        self.speedLimitSpin.setSuffix(_translate("mainWindow", " Mbps"))
        self.downloadLocationBtn.setText(_translate("mainWindow", "Select Download Location"))
        self.exchangeURLLbl.setText(_translate("mainWindow", "Exchange URL"))
        self.sharedLocationInput.setPlaceholderText(_translate("mainWindow", "This is the folder you are sharing"))
        self.downloadLocationInput.setPlaceholderText(_translate("mainWindow", "Leave it blank to set everytime you download"))
        self.exchangeURLInput.setPlaceholderText(_translate("mainWindow", "Leave blank to share personally."))
        self.label_5.setText(_translate("mainWindow", "Don\'t randomly hit your mouse. It hurts!"))
        self.toggleShareBtn.setText(_translate("mainWindow", "Start sharing"))
        self.label_2.setText(_translate("mainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Sharing at</span></p></body></html>"))
        self.urlLabel.setText(_translate("mainWindow", "Not running"))
        self.groupBox.setTitle(_translate("mainWindow", "     Stats:"))
        self.connectedStatsLbl.setText(_translate("mainWindow", "Connected"))
        self.stats_connected.setText(_translate("mainWindow", "0"))
        self.label_8.setText(_translate("mainWindow", "Transferred"))
        self.stats_files.setToolTip(_translate("mainWindow", "<html><head/><body><p>Files</p></body></html>"))
        self.stats_files.setText(_translate("mainWindow", "0"))
        self.stats_bytes.setToolTip(_translate("mainWindow", "<html><head/><body><p>Data</p></body></html>"))
        self.stats_bytes.setText(_translate("mainWindow", "0"))
        self.trayCB.setText(_translate("mainWindow", "Minimize to tray on exit"))
        self.projectLink.setText(_translate("mainWindow", "<html><head/><body><p>Fork it on <a href=\"https://github.com/21lane/\"><span style=\" text-decoration: underline; color:#0000ff;\">GitHub</span></a></p></body></html>"))
        self.developerLink.setText(_translate("mainWindow", "<html><head/><body><p align=\"right\">By <a href=\"https://github.com/himanshub16\"><span style=\" text-decoration: underline; color:#0000ff;\">Himanshu Shekhar</span></a></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settingsTab), _translate("mainWindow", "Settings"))
        self.label.setText(_translate("mainWindow", "Double click row to browse"))
        self.userListTable.setSortingEnabled(True)
        item = self.userListTable.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "Index"))
        item = self.userListTable.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "Shared size"))
        item = self.userListTable.horizontalHeaderItem(2)
        item.setText(_translate("mainWindow", "Public Name"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.usersListTab), _translate("mainWindow", "Current Users"))
        self.browserInput.setPlaceholderText(_translate("mainWindow", "Search / Enter path"))
        self.browserTable.setSortingEnabled(True)
        item = self.browserTable.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "Index"))
        item = self.browserTable.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "Download"))
        item = self.browserTable.horizontalHeaderItem(2)
        item.setText(_translate("mainWindow", "Size"))
        item = self.browserTable.horizontalHeaderItem(3)
        item.setText(_translate("mainWindow", "Type"))
        item = self.browserTable.horizontalHeaderItem(4)
        item.setText(_translate("mainWindow", "Name"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.browserTab), _translate("mainWindow", "Browser"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.downloadsTab), _translate("mainWindow", "Downloads"))

import resources_rc
